-- Antes el banco de preguntas era un único ejercicio hardcodeado en TS
-- (`_bank.ts`, `BANK = [DEMO_QUESTION]`). Esta tabla es el banco real:
-- 16 preguntas por nivel CEFR (80 en total), cada una con 4 opciones,
-- explicación de acierto y de error — igual que el ejercicio de referencia
-- del diseño original, pero persistido y con contenido real por nivel.
create table practice_questions (
  id                    uuid primary key default gen_random_uuid(),
  cefr_tier             cefr_level not null,
  position              integer not null,
  category              text not null,
  xp_reward             integer not null,
  prompt                text not null,
  source_text           text not null,
  options               jsonb not null,
  correct_option_id     text not null,
  explanation_correct   text not null,
  explanation_wrong     text not null,

  unique (cefr_tier, position)
);

alter table practice_questions enable row level security;

create policy "preguntas de práctica visibles para autenticados"
  on practice_questions for select using (auth.role() = 'authenticated');

create policy "docentes gestionan preguntas de práctica"
  on practice_questions for all using (is_staff()) with check (is_staff());

-- ── A1 ──────────────────────────────────────────────────────────────────────
insert into practice_questions (cefr_tier, position, category, xp_reward, prompt, source_text, options, correct_option_id, explanation_correct, explanation_wrong) values
('A1', 1, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Hola, ¿cómo estás?"',
 '[{"id":"a","key":"A","text":"Hello, how are you?"},{"id":"b","key":"B","text":"Hello, how you are?"},{"id":"c","key":"C","text":"Hello, how is you?"},{"id":"d","key":"D","text":"Hi, how you doing today morning?"}]'::jsonb,
 'a', 'En preguntas con "how", el verbo "to be" va antes del sujeto.', 'En inglés el verbo "to be" va antes del sujeto en preguntas.'),
('A1', 2, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Me llamo Ana."',
 '[{"id":"a","key":"A","text":"My name is Ana."},{"id":"b","key":"B","text":"I call me Ana."},{"id":"c","key":"C","text":"My name are Ana."},{"id":"d","key":"D","text":"I am name Ana."}]'::jsonb,
 'a', '"My name is" es la forma natural de presentarse.', '"Llamarse" no se traduce literalmente como "to call oneself" en presentaciones.'),
('A1', 3, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Tengo un gato."',
 '[{"id":"a","key":"A","text":"I have a cat."},{"id":"b","key":"B","text":"I has a cat."},{"id":"c","key":"C","text":"I having a cat."},{"id":"d","key":"D","text":"I am have a cat."}]'::jsonb,
 'a', 'Con "I" el verbo "have" no lleva -s.', '"Has" sólo se usa con he/she/it.'),
('A1', 4, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Ella es mi hermana."',
 '[{"id":"a","key":"A","text":"She is my sister."},{"id":"b","key":"B","text":"She are my sister."},{"id":"c","key":"C","text":"Her is my sister."},{"id":"d","key":"D","text":"She be my sister."}]'::jsonb,
 'a', 'Con "she" el verbo "to be" es "is".', '"Are" se usa con you/we/they, no con she.'),
('A1', 5, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"¿Dónde está el baño?"',
 '[{"id":"a","key":"A","text":"Where is the bathroom?"},{"id":"b","key":"B","text":"Where the bathroom is?"},{"id":"c","key":"C","text":"Where are the bathroom?"},{"id":"d","key":"D","text":"Where be the bathroom?"}]'::jsonb,
 'a', 'En preguntas, el verbo "is" va antes del sujeto.', 'El orden pregunta-verbo-sujeto es obligatorio en inglés.'),
('A1', 6, 'VOCABULARIO', 20, 'Elige la traducción correcta', '"Son las tres."',
 '[{"id":"a","key":"A","text":"It is three o''clock."},{"id":"b","key":"B","text":"They are three o''clock."},{"id":"c","key":"C","text":"Is three o''clock."},{"id":"d","key":"D","text":"It are three o''clock."}]'::jsonb,
 'a', 'Para decir la hora en inglés se usa "it is", nunca "they".', 'La hora siempre usa el sujeto impersonal "it", no "they".'),
('A1', 7, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Yo bebo agua."',
 '[{"id":"a","key":"A","text":"I drink water."},{"id":"b","key":"B","text":"I drinks water."},{"id":"c","key":"C","text":"I am drink water."},{"id":"d","key":"D","text":"I drinking water."}]'::jsonb,
 'a', 'Presente simple con "I": el verbo va sin cambios.', 'La "-s" sólo se agrega con he/she/it en presente simple.'),
('A1', 8, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Él trabaja aquí."',
 '[{"id":"a","key":"A","text":"He works here."},{"id":"b","key":"B","text":"He work here."},{"id":"c","key":"C","text":"He working here."},{"id":"d","key":"D","text":"He are working here."}]'::jsonb,
 'a', 'Con "he" el verbo en presente simple lleva "-s": works.', 'Falta la "-s" obligatoria con la tercera persona singular.'),
('A1', 9, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Nosotros somos estudiantes."',
 '[{"id":"a","key":"A","text":"We are students."},{"id":"b","key":"B","text":"We is students."},{"id":"c","key":"C","text":"We am students."},{"id":"d","key":"D","text":"We be students."}]'::jsonb,
 'a', 'Con "we" el verbo "to be" es "are".', '"Is" y "am" no se usan con "we".'),
('A1', 10, 'VOCABULARIO', 20, 'Elige la traducción correcta', '"Ella tiene veinte años."',
 '[{"id":"a","key":"A","text":"She is twenty years old."},{"id":"b","key":"B","text":"She has twenty years."},{"id":"c","key":"C","text":"She have twenty years old."},{"id":"d","key":"D","text":"She is twenty years."}]'::jsonb,
 'a', 'En inglés la edad se expresa con "to be", no con "to have".', 'Para la edad se usa "to be ... years old", no "have".'),
('A1', 11, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"¿Cuántos libros tienes?"',
 '[{"id":"a","key":"A","text":"How many books do you have?"},{"id":"b","key":"B","text":"How much books you have?"},{"id":"c","key":"C","text":"How many books you have?"},{"id":"d","key":"D","text":"How many book do you have?"}]'::jsonb,
 'a', '"Books" es contable, se usa "how many"; y la pregunta necesita "do".', '"How much" es para incontables; falta el auxiliar "do" en preguntas.'),
('A1', 12, 'VOCABULARIO', 20, 'Elige la traducción correcta', '"Hace calor hoy."',
 '[{"id":"a","key":"A","text":"It is hot today."},{"id":"b","key":"B","text":"It has hot today."},{"id":"c","key":"C","text":"Today is hace hot."},{"id":"d","key":"D","text":"It do hot today."}]'::jsonb,
 'a', 'El clima se describe con "it is", no con "have".', 'Para el clima en inglés se usa "to be", no "to have".'),
('A1', 13, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Me gusta el café."',
 '[{"id":"a","key":"A","text":"I like coffee."},{"id":"b","key":"B","text":"I like the coffee."},{"id":"c","key":"C","text":"I likes coffee."},{"id":"d","key":"D","text":"Me gusts coffee."}]'::jsonb,
 'a', 'Al hablar de algo en general no se usa "the".', '"The" sólo se usa para algo específico, no para gustos generales.'),
('A1', 14, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Ellos viven en Madrid."',
 '[{"id":"a","key":"A","text":"They live in Madrid."},{"id":"b","key":"B","text":"They lives in Madrid."},{"id":"c","key":"C","text":"They living in Madrid."},{"id":"d","key":"D","text":"They are live in Madrid."}]'::jsonb,
 'a', 'Con "they" el verbo no lleva "-s".', 'La "-s" es sólo para he/she/it, no para "they".'),
('A1', 15, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"¿Qué hora es?"',
 '[{"id":"a","key":"A","text":"What time is it?"},{"id":"b","key":"B","text":"What time it is?"},{"id":"c","key":"C","text":"What hour is it?"},{"id":"d","key":"D","text":"What time are it?"}]'::jsonb,
 'a', 'Es la forma fija en inglés para preguntar la hora.', 'El orden verbo-sujeto es obligatorio en preguntas; "hour" no se usa así.'),
('A1', 16, 'GRAMÁTICA', 20, 'Elige la traducción correcta', '"Mi casa es grande."',
 '[{"id":"a","key":"A","text":"My house is big."},{"id":"b","key":"B","text":"My house are big."},{"id":"c","key":"C","text":"My house is bigger."},{"id":"d","key":"D","text":"My house be big."}]'::jsonb,
 'a', '"House" es singular, así que el verbo es "is".', '"Are" es para plural; "house" es singular.');

-- ── A2 ──────────────────────────────────────────────────────────────────────
insert into practice_questions (cefr_tier, position, category, xp_reward, prompt, source_text, options, correct_option_id, explanation_correct, explanation_wrong) values
('A2', 1, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ayer fui al cine."',
 '[{"id":"a","key":"A","text":"Yesterday I went to the cinema."},{"id":"b","key":"B","text":"Yesterday I go to the cinema."},{"id":"c","key":"C","text":"Yesterday I goed to the cinema."},{"id":"d","key":"D","text":"Yesterday I have gone to the cinema."}]'::jsonb,
 'a', '"Go" es irregular, su pasado es "went".', '"Goed" no existe; con "yesterday" se usa pasado simple, no presente perfecto.'),
('A2', 2, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ella no puede nadar."',
 '[{"id":"a","key":"A","text":"She can''t swim."},{"id":"b","key":"B","text":"She not can swim."},{"id":"c","key":"C","text":"She don''t can swim."},{"id":"d","key":"D","text":"She cannot to swim."}]'::jsonb,
 'a', 'La negación de "can" se forma con "can''t" + verbo base.', '"Can" no se combina con "don''t" ni lleva "to" antes del verbo.'),
('A2', 3, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Hay dos perros en el jardín."',
 '[{"id":"a","key":"A","text":"There are two dogs in the garden."},{"id":"b","key":"B","text":"There is two dogs in the garden."},{"id":"c","key":"C","text":"There have two dogs in the garden."},{"id":"d","key":"D","text":"They are two dogs in the garden."}]'::jsonb,
 'a', 'Con sustantivos plurales se usa "there are".', '"Is" es para singular; "have" no se usa en esta estructura.'),
('A2', 4, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Mi hermano es más alto que yo."',
 '[{"id":"a","key":"A","text":"My brother is taller than me."},{"id":"b","key":"B","text":"My brother is more tall than me."},{"id":"c","key":"C","text":"My brother is taller that me."},{"id":"d","key":"D","text":"My brother is the tallest than me."}]'::jsonb,
 'a', 'Adjetivos cortos forman el comparativo con "-er".', 'No se usa "more" con adjetivos cortos, y el comparativo usa "than", no "that".'),
('A2', 5, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ella se despierta a las siete."',
 '[{"id":"a","key":"A","text":"She wakes up at seven."},{"id":"b","key":"B","text":"She wake up at seven."},{"id":"c","key":"C","text":"She is waking up at seven every day."},{"id":"d","key":"D","text":"She waked up at seven."}]'::jsonb,
 'a', 'Rutinas usan presente simple; con "she" el verbo lleva "-s".', 'Falta la "-s" de tercera persona, o se usó una forma incorrecta del verbo.'),
('A2', 6, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"No tengo dinero."',
 '[{"id":"a","key":"A","text":"I don''t have any money."},{"id":"b","key":"B","text":"I don''t have some money."},{"id":"c","key":"C","text":"I not have money."},{"id":"d","key":"D","text":"I haven''t some money."}]'::jsonb,
 'a', 'En negaciones se usa "any", no "some".', '"Some" se usa en afirmaciones; en negaciones corresponde "any".'),
('A2', 7, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"¿Puedes ayudarme, por favor?"',
 '[{"id":"a","key":"A","text":"Can you help me, please?"},{"id":"b","key":"B","text":"You can help me, please?"},{"id":"c","key":"C","text":"Can you to help me, please?"},{"id":"d","key":"D","text":"Do you can help me, please?"}]'::jsonb,
 'a', 'Preguntas con "can" invierten el orden: can + sujeto + verbo.', '"Can" no lleva "to" ni se combina con "do".'),
('A2', 8, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Fuimos a la playa el sábado pasado."',
 '[{"id":"a","key":"A","text":"We went to the beach last Saturday."},{"id":"b","key":"B","text":"We go to the beach last Saturday."},{"id":"c","key":"C","text":"We have went to the beach last Saturday."},{"id":"d","key":"D","text":"We were go to the beach last Saturday."}]'::jsonb,
 'a', '"Went" es el pasado simple de "go", correcto con "last Saturday".', 'Con expresiones de tiempo pasado cerrado se usa pasado simple, no presente ni presente perfecto.'),
('A2', 9, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ella está cocinando ahora mismo."',
 '[{"id":"a","key":"A","text":"She is cooking right now."},{"id":"b","key":"B","text":"She cooks right now."},{"id":"c","key":"C","text":"She is cook right now."},{"id":"d","key":"D","text":"She cooking right now."}]'::jsonb,
 'a', 'Una acción en curso ahora usa presente continuo: is + verbo-ing.', 'Falta el verbo "to be" o la forma "-ing" está incompleta.'),
('A2', 10, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Este libro es más interesante que ese."',
 '[{"id":"a","key":"A","text":"This book is more interesting than that one."},{"id":"b","key":"B","text":"This book is interesanter than that one."},{"id":"c","key":"C","text":"This book is the most interesting than that one."},{"id":"d","key":"D","text":"This book is interesting more than that one."}]'::jsonb,
 'a', 'Adjetivos largos usan "more" + adjetivo para el comparativo.', 'No se puede combinar "the most" con "than"; el orden de "more" también importa.'),
('A2', 11, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ellos no fueron a la fiesta."',
 '[{"id":"a","key":"A","text":"They didn''t go to the party."},{"id":"b","key":"B","text":"They not went to the party."},{"id":"c","key":"C","text":"They didn''t went to the party."},{"id":"d","key":"D","text":"They doesn''t go to the party."}]'::jsonb,
 'a', 'Negaciones en pasado usan "didn''t" + verbo base.', 'Con "didn''t" el verbo vuelve a su forma base, no al pasado.'),
('A2', 12, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"¿Qué haces normalmente los domingos?"',
 '[{"id":"a","key":"A","text":"What do you usually do on Sundays?"},{"id":"b","key":"B","text":"What you usually do on Sundays?"},{"id":"c","key":"C","text":"What do you usually doing on Sundays?"},{"id":"d","key":"D","text":"What usually do you do on Sundays?"}]'::jsonb,
 'a', 'Preguntas en presente simple necesitan el auxiliar "do" antes del sujeto.', 'Falta el auxiliar "do" en la posición correcta, o el verbo está mal formado.'),
('A2', 13, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Necesito comprar algo de pan."',
 '[{"id":"a","key":"A","text":"I need to buy some bread."},{"id":"b","key":"B","text":"I need buy some bread."},{"id":"c","key":"C","text":"I need to buying some bread."},{"id":"d","key":"D","text":"I need to buy any bread."}]'::jsonb,
 'a', 'Después de "need" se usa "to" + verbo base.', 'Falta el "to", o se usó una forma incorrecta del verbo; "any" no va en afirmaciones.'),
('A2', 14, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ella trabajó todo el día ayer."',
 '[{"id":"a","key":"A","text":"She worked all day yesterday."},{"id":"b","key":"B","text":"She works all day yesterday."},{"id":"c","key":"C","text":"She was work all day yesterday."},{"id":"d","key":"D","text":"She has worked all day yesterday."}]'::jsonb,
 'a', '"Worked" es el pasado simple regular de "work".', 'Con "yesterday" se necesita pasado simple, no presente ni presente perfecto.'),
('A2', 15, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Mi cuarto es tan grande como el tuyo."',
 '[{"id":"a","key":"A","text":"My room is as big as yours."},{"id":"b","key":"B","text":"My room is so big as yours."},{"id":"c","key":"C","text":"My room is as big than yours."},{"id":"d","key":"D","text":"My room is big as yours."}]'::jsonb,
 'a', 'La comparación de igualdad se forma con "as + adjetivo + as".', 'No se combina "as" con "than", y no puede faltar el primer "as".'),
('A2', 16, 'GRAMÁTICA', 25, 'Elige la traducción correcta', '"Ellos estaban viendo la tele cuando llegué."',
 '[{"id":"a","key":"A","text":"They were watching TV when I arrived."},{"id":"b","key":"B","text":"They was watching TV when I arrived."},{"id":"c","key":"C","text":"They were watch TV when I arrived."},{"id":"d","key":"D","text":"They are watching TV when I arrived."}]'::jsonb,
 'a', 'Pasado continuo con "they" usa "were" + verbo-ing.', '"Was" no se usa con "they"; el verbo necesita la forma "-ing".');

-- ── B1 ──────────────────────────────────────────────────────────────────────
insert into practice_questions (cefr_tier, position, category, xp_reward, prompt, source_text, options, correct_option_id, explanation_correct, explanation_wrong) values
('B1', 1, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"He vivido aquí desde 2015."',
 '[{"id":"a","key":"A","text":"I have lived here since 2015."},{"id":"b","key":"B","text":"I live here since 2015."},{"id":"c","key":"C","text":"I lived here since 2015."},{"id":"d","key":"D","text":"I am living here since 2015."}]'::jsonb,
 'a', '"Since" con una acción que continúa hasta ahora requiere presente perfecto.', 'Con "since" y una situación vigente se usa presente perfecto, no pasado ni presente simple.'),
('B1', 2, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Deberías estudiar más para el examen."',
 '[{"id":"a","key":"A","text":"You should study more for the exam."},{"id":"b","key":"B","text":"You should to study more for the exam."},{"id":"c","key":"C","text":"You must studying more for the exam."},{"id":"d","key":"D","text":"You should studies more for the exam."}]'::jsonb,
 'a', 'Después de "should" el verbo va en forma base, sin "to".', 'Los modales como "should" nunca llevan "to" ni "-s"/"-ing" después.'),
('B1', 3, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Si llueve, no saldremos."',
 '[{"id":"a","key":"A","text":"If it rains, we won''t go out."},{"id":"b","key":"B","text":"If it will rain, we won''t go out."},{"id":"c","key":"C","text":"If it rains, we don''t go out."},{"id":"d","key":"D","text":"If it rain, we won''t go out."}]'::jsonb,
 'a', 'En el primer condicional, la cláusula con "if" va en presente simple.', 'No se usa "will" después de "if"; el verbo necesita concordancia correcta.'),
('B1', 4, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Ya he terminado mi tarea."',
 '[{"id":"a","key":"A","text":"I have already finished my homework."},{"id":"b","key":"B","text":"I already finished my homework since morning."},{"id":"c","key":"C","text":"I have already finish my homework."},{"id":"d","key":"D","text":"I already have finished my homework since."}]'::jsonb,
 'a', '"Already" con presente perfecto confirma que la acción se completó recientemente.', 'El participio debe ser "finished", no "finish"; y el orden de "already" importa.'),
('B1', 5, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Voy a viajar a Japón el próximo mes."',
 '[{"id":"a","key":"A","text":"I am going to travel to Japan next month."},{"id":"b","key":"B","text":"I will going to travel to Japan next month."},{"id":"c","key":"C","text":"I am go to travel to Japan next month."},{"id":"d","key":"D","text":"I go to travel to Japan next month."}]'::jsonb,
 'a', '"Be going to" expresa planes futuros ya decididos.', 'No se combina "will" con "going to"; falta la forma correcta del verbo "be".'),
('B1', 6, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Tienes que terminar esto hoy."',
 '[{"id":"a","key":"A","text":"You must finish this today."},{"id":"b","key":"B","text":"You must to finish this today."},{"id":"c","key":"C","text":"You must finishing this today."},{"id":"d","key":"D","text":"You must finished this today."}]'::jsonb,
 'a', '"Must" va seguido del verbo en forma base.', '"Must" nunca lleva "to" antes del verbo.'),
('B1', 7, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Nunca he estado en Europa."',
 '[{"id":"a","key":"A","text":"I have never been to Europe."},{"id":"b","key":"B","text":"I never was in Europe."},{"id":"c","key":"C","text":"I have never went to Europe."},{"id":"d","key":"D","text":"I never have been to Europe."}]'::jsonb,
 'a', 'Experiencias de vida usan presente perfecto: "have + never + participio".', 'El participio de "go/be" es "been", no "went"; el orden de "never" también importa.'),
('B1', 8, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Ella acaba de llegar."',
 '[{"id":"a","key":"A","text":"She has just arrived."},{"id":"b","key":"B","text":"She just arrived now."},{"id":"c","key":"C","text":"She has just arrive."},{"id":"d","key":"D","text":"She is just arriving."}]'::jsonb,
 'a', '"Just" con presente perfecto indica que algo pasó hace muy poco.', 'El participio correcto es "arrived"; el presente continuo no expresa esta idea.'),
('B1', 9, 'VOCABULARIO', 30, 'Elige la traducción correcta', '"Busqué esa palabra en el diccionario."',
 '[{"id":"a","key":"A","text":"I looked up that word in the dictionary."},{"id":"b","key":"B","text":"I looked that word up in a dictionary up."},{"id":"c","key":"C","text":"I look up that word in the dictionary."},{"id":"d","key":"D","text":"I have look up that word in the dictionary."}]'::jsonb,
 'a', '"Look up" es un phrasal verb; en pasado simple es "looked up".', 'El phrasal verb no se repite ni se deja sin conjugar.'),
('B1', 10, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Si tuviera más tiempo, aprendería francés."',
 '[{"id":"a","key":"A","text":"If I had more time, I would learn French."},{"id":"b","key":"B","text":"If I have more time, I would learn French."},{"id":"c","key":"C","text":"If I had more time, I will learn French."},{"id":"d","key":"D","text":"If I would have more time, I would learn French."}]'::jsonb,
 'a', 'El segundo condicional usa pasado simple + "would" + verbo base.', 'No se combina "if" + presente con "would", ni "would" en ambas cláusulas.'),
('B1', 11, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"¿Has visto esa película?"',
 '[{"id":"a","key":"A","text":"Have you seen that movie?"},{"id":"b","key":"B","text":"Did you have seen that movie?"},{"id":"c","key":"C","text":"Have you saw that movie?"},{"id":"d","key":"D","text":"You have seen that movie?"}]'::jsonb,
 'a', 'Preguntas en presente perfecto invierten "have" y el sujeto.', 'El participio correcto es "seen", no "saw"; y "did" no se combina con "have".'),
('B1', 12, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Ella podría ayudarte si se lo pides."',
 '[{"id":"a","key":"A","text":"She could help you if you ask her."},{"id":"b","key":"B","text":"She could help you if you asked her."},{"id":"c","key":"C","text":"She can help you if you will ask her."},{"id":"d","key":"D","text":"She could helps you if you ask her."}]'::jsonb,
 'a', 'En este tipo de condicional, la cláusula con "if" va en presente.', 'Mezclar tiempos o agregar "-s" al verbo modal rompe la estructura.'),
('B1', 13, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Llevo dos horas esperando el autobús."',
 '[{"id":"a","key":"A","text":"I have been waiting for the bus for two hours."},{"id":"b","key":"B","text":"I am waiting for the bus for two hours."},{"id":"c","key":"C","text":"I wait for the bus for two hours."},{"id":"d","key":"D","text":"I have waited for the bus during two hours."}]'::jsonb,
 'a', 'Una acción que empezó en el pasado y continúa se expresa con presente perfecto continuo.', 'El presente simple o continuo no marca duración desde el pasado hasta ahora.'),
('B1', 14, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Se supone que debemos entregar esto mañana."',
 '[{"id":"a","key":"A","text":"We are supposed to hand this in tomorrow."},{"id":"b","key":"B","text":"We are supposed hand this in tomorrow."},{"id":"c","key":"C","text":"We supposed to hand this in tomorrow."},{"id":"d","key":"D","text":"We are suppose to hand this in tomorrow."}]'::jsonb,
 'a', '"Be supposed to" necesita el verbo "be" conjugado y "to" antes del verbo.', 'Falta el "to", o el verbo "be" está mal conjugado o ausente.'),
('B1', 15, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"No voy a rendirme."',
 '[{"id":"a","key":"A","text":"I am not going to give up."},{"id":"b","key":"B","text":"I don''t going to give up."},{"id":"c","key":"C","text":"I am not go to give up."},{"id":"d","key":"D","text":"I not am going to give up."}]'::jsonb,
 'a', 'La negación de "be going to" se forma con "am/is/are + not".', 'No se usa "don''t" con "going to"; el orden de "not" también importa.'),
('B1', 16, 'GRAMÁTICA', 30, 'Elige la traducción correcta', '"Cuando llegues, llámame."',
 '[{"id":"a","key":"A","text":"When you arrive, call me."},{"id":"b","key":"B","text":"When you will arrive, call me."},{"id":"c","key":"C","text":"When you arrived, call me."},{"id":"d","key":"D","text":"When you arriving, call me."}]'::jsonb,
 'a', 'Tras "when" referido a futuro, se usa presente simple, no "will".', '"Will" no se usa después de conectores temporales como "when" al hablar de futuro.');

-- ── B2 ──────────────────────────────────────────────────────────────────────
insert into practice_questions (cefr_tier, position, category, xp_reward, prompt, source_text, options, correct_option_id, explanation_correct, explanation_wrong) values
('B2', 1, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"La casa fue construida en 1990."',
 '[{"id":"a","key":"A","text":"The house was built in 1990."},{"id":"b","key":"B","text":"The house was build in 1990."},{"id":"c","key":"C","text":"The house has built in 1990."},{"id":"d","key":"D","text":"The house is built in 1990."}]'::jsonb,
 'a', 'Voz pasiva en pasado: was/were + participio.', 'El participio correcto es "built", no "build"; y el tiempo verbal debe coincidir con "1990".'),
('B2', 2, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Ella dijo que estaba cansada."',
 '[{"id":"a","key":"A","text":"She said that she was tired."},{"id":"b","key":"B","text":"She said that she is tired."},{"id":"c","key":"C","text":"She said that she were tired."},{"id":"d","key":"D","text":"She says that she was tired."}]'::jsonb,
 'a', 'En estilo indirecto, el presente pasa a pasado (backshift).', 'El verbo debe retroceder un tiempo respecto al original.'),
('B2', 3, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Si hubiera estudiado más, habría aprobado."',
 '[{"id":"a","key":"A","text":"If I had studied more, I would have passed."},{"id":"b","key":"B","text":"If I studied more, I would have passed."},{"id":"c","key":"C","text":"If I had studied more, I would pass."},{"id":"d","key":"D","text":"If I would have studied more, I would have passed."}]'::jsonb,
 'a', 'El tercer condicional usa pasado perfecto + "would have" + participio.', 'No se usa "would" en la cláusula con "if", ni se mezcla con el segundo condicional.'),
('B2', 4, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"El hombre que vive al lado es médico."',
 '[{"id":"a","key":"A","text":"The man who lives next door is a doctor."},{"id":"b","key":"B","text":"The man which lives next door is a doctor."},{"id":"c","key":"C","text":"The man who live next door is a doctor."},{"id":"d","key":"D","text":"The man is living next door is a doctor."}]'::jsonb,
 'a', '"Who" se usa para personas en cláusulas relativas.', '"Which" es para cosas, no personas; y el verbo necesita concordar en tercera persona.'),
('B2', 5, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"El informe está siendo revisado ahora mismo."',
 '[{"id":"a","key":"A","text":"The report is being reviewed right now."},{"id":"b","key":"B","text":"The report is reviewed right now."},{"id":"c","key":"C","text":"The report is being review right now."},{"id":"d","key":"D","text":"The report being reviewed right now."}]'::jsonb,
 'a', 'Voz pasiva continua: is/are + being + participio.', 'Falta "being" o el verbo "to be" auxiliar necesario.'),
('B2', 6, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Me preguntó dónde vivía."',
 '[{"id":"a","key":"A","text":"He asked me where I lived."},{"id":"b","key":"B","text":"He asked me where do I live."},{"id":"c","key":"C","text":"He asked me where I live."},{"id":"d","key":"D","text":"He asked me where did I lived."}]'::jsonb,
 'a', 'En preguntas indirectas no se usa el auxiliar "do", y el tiempo retrocede.', 'Las preguntas indirectas no llevan inversión ni el auxiliar "do".'),
('B2', 7, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Ojalá pudiera hablar francés con fluidez."',
 '[{"id":"a","key":"A","text":"I wish I could speak French fluently."},{"id":"b","key":"B","text":"I wish I can speak French fluently."},{"id":"c","key":"C","text":"I wish I would speak French fluently."},{"id":"d","key":"D","text":"I wish I could spoke French fluently."}]'::jsonb,
 'a', '"Wish" + pasado simple/could expresa un deseo irreal en el presente.', '"Wish" no se combina con "can" ni con dos formas verbales pasadas seguidas.'),
('B2', 8, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"A pesar de la lluvia, salimos a caminar."',
 '[{"id":"a","key":"A","text":"Despite the rain, we went for a walk."},{"id":"b","key":"B","text":"Despite of the rain, we went for a walk."},{"id":"c","key":"C","text":"Although the rain, we went for a walk."},{"id":"d","key":"D","text":"Despite it was raining, we went for a walk."}]'::jsonb,
 'a', '"Despite" va seguido directamente de un sustantivo o gerundio, sin "of".', '"Despite" no lleva "of"; y "although" necesita una cláusula completa, no solo un sustantivo.'),
('B2', 9, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Este es el libro del que te hablé."',
 '[{"id":"a","key":"A","text":"This is the book I told you about."},{"id":"b","key":"B","text":"This is the book that I told you."},{"id":"c","key":"C","text":"This is the book about I told you."},{"id":"d","key":"D","text":"This is the book which I told you about it."}]'::jsonb,
 'a', 'La preposición "about" puede ir al final de la cláusula relativa en inglés informal.', 'Falta la preposición "about", o se repite el objeto innecesariamente.'),
('B2', 10, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Se dice que la empresa va a cerrar."',
 '[{"id":"a","key":"A","text":"The company is said to be closing."},{"id":"b","key":"B","text":"It is said the company is closing."},{"id":"c","key":"C","text":"The company is says to be closing."},{"id":"d","key":"D","text":"The company said to be closing."}]'::jsonb,
 'a', 'Estructura pasiva con verbos de opinión: sujeto + is said to + infinitivo.', 'El verbo "say" debe ir en participio ("said"), y necesita el auxiliar "to be".'),
('B2', 11, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"No solo llegó tarde, sino que además olvidó los documentos."',
 '[{"id":"a","key":"A","text":"Not only did he arrive late, but he also forgot the documents."},{"id":"b","key":"B","text":"Not only he arrived late, but he also forgot the documents."},{"id":"c","key":"C","text":"Not only did he arrived late, but also forgot the documents."},{"id":"d","key":"D","text":"He not only arrived late, but also he forgot the documents."}]'::jsonb,
 'a', '"Not only" al inicio de la oración exige inversión del auxiliar.', 'Tras "not only" al inicio se necesita inversión (did + sujeto) y el verbo en forma base.'),
('B2', 12, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Cuanto más practicas, mejor te vuelves."',
 '[{"id":"a","key":"A","text":"The more you practice, the better you become."},{"id":"b","key":"B","text":"More you practice, better you become."},{"id":"c","key":"C","text":"The more you practice, the best you become."},{"id":"d","key":"D","text":"The most you practice, the better you become."}]'::jsonb,
 'a', 'La estructura comparativa doble es "the + comparativo, the + comparativo".', 'No puede faltar "the" al inicio de cada cláusula, ni usarse el superlativo.'),
('B2', 13, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Deberías haber llamado antes."',
 '[{"id":"a","key":"A","text":"You should have called earlier."},{"id":"b","key":"B","text":"You should call earlier."},{"id":"c","key":"C","text":"You should have call earlier."},{"id":"d","key":"D","text":"You should had called earlier."}]'::jsonb,
 'a', '"Should have + participio" expresa un consejo sobre algo pasado que no se hizo.', 'Falta el participio correcto o se combinó mal el modal con "have".'),
('B2', 14, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"El proyecto será terminado para el viernes."',
 '[{"id":"a","key":"A","text":"The project will have been finished by Friday."},{"id":"b","key":"B","text":"The project will be finished until Friday."},{"id":"c","key":"C","text":"The project will finished by Friday."},{"id":"d","key":"D","text":"The project will has been finished by Friday."}]'::jsonb,
 'a', 'El futuro perfecto pasivo expresa una acción completada antes de un plazo.', '"Until" no marca un plazo límite (se usa "by"); y falta el auxiliar correcto.'),
('B2', 15, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"Es hora de que tomes una decisión."',
 '[{"id":"a","key":"A","text":"It''s time you made a decision."},{"id":"b","key":"B","text":"It''s time you make a decision."},{"id":"c","key":"C","text":"It''s time to you make a decision."},{"id":"d","key":"D","text":"It''s time that you will make a decision."}]'::jsonb,
 'a', '"It''s time" + sujeto se combina con pasado simple aunque hable del presente/futuro.', 'Esta estructura no admite presente simple ni "will" después.'),
('B2', 16, 'GRAMÁTICA', 35, 'Elige la traducción correcta', '"A menos que llames, no sabremos qué pasó."',
 '[{"id":"a","key":"A","text":"Unless you call, we won''t know what happened."},{"id":"b","key":"B","text":"Unless you will call, we won''t know what happened."},{"id":"c","key":"C","text":"Unless you don''t call, we won''t know what happened."},{"id":"d","key":"D","text":"If you don''t unless call, we won''t know what happened."}]'::jsonb,
 'a', '"Unless" ya significa "si no", así que no lleva negación adicional ni "will".', '"Unless" no se combina con "will" ni con otra negación como "don''t".');

-- ── C1 ──────────────────────────────────────────────────────────────────────
insert into practice_questions (cefr_tier, position, category, xp_reward, prompt, source_text, options, correct_option_id, explanation_correct, explanation_wrong) values
('C1', 1, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Rara vez había visto algo tan impresionante."',
 '[{"id":"a","key":"A","text":"Rarely had I seen something so impressive."},{"id":"b","key":"B","text":"Rarely I had seen something so impressive."},{"id":"c","key":"C","text":"Rarely I have seen something so impressive."},{"id":"d","key":"D","text":"Rarely had seen I something so impressive."}]'::jsonb,
 'a', 'Adverbios negativos como "rarely" al inicio requieren inversión sujeto-auxiliar.', 'Sin la inversión correcta (auxiliar antes del sujeto), la estructura enfática es incorrecta.'),
('C1', 2, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Podría haberlo hecho de otra manera."',
 '[{"id":"a","key":"A","text":"I could have done it differently."},{"id":"b","key":"B","text":"I could have did it differently."},{"id":"c","key":"C","text":"I could had done it differently."},{"id":"d","key":"D","text":"I could have done it different."}]'::jsonb,
 'a', '"Could have + participio" habla de una posibilidad pasada; "differently" es el adverbio correcto.', 'El participio correcto es "done", no "did"; y se necesita un adverbio, no un adjetivo.'),
('C1', 3, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"No había terminado el informe cuando llegó mi jefe."',
 '[{"id":"a","key":"A","text":"I hadn''t finished the report when my boss arrived."},{"id":"b","key":"B","text":"I didn''t finish the report when my boss arrived."},{"id":"c","key":"C","text":"I hadn''t finish the report when my boss arrived."},{"id":"d","key":"D","text":"I haven''t finished the report when my boss arrived."}]'::jsonb,
 'a', 'Una acción anterior a otra en pasado usa pasado perfecto.', 'El participio correcto es "finished"; y el pasado perfecto, no el presente perfecto, marca anterioridad en el pasado.'),
('C1', 4, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Se rumorea que la empresa será vendida."',
 '[{"id":"a","key":"A","text":"The company is rumoured to be sold."},{"id":"b","key":"B","text":"It is rumoured that company will be sale."},{"id":"c","key":"C","text":"The company is rumour to be sold."},{"id":"d","key":"D","text":"The company is rumoured to being sold."}]'::jsonb,
 'a', 'Estructura pasiva con verbos de rumor: sujeto + is rumoured + infinitivo pasivo.', 'El verbo debe ir en participio ("rumoured"), y el infinitivo pasivo es "to be sold", no "to being sold".'),
('C1', 5, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Con tal de que termines a tiempo, puedes irte temprano."',
 '[{"id":"a","key":"A","text":"As long as you finish on time, you can leave early."},{"id":"b","key":"B","text":"As long as you will finish on time, you can leave early."},{"id":"c","key":"C","text":"As long you finish on time, you can leave early."},{"id":"d","key":"D","text":"As long as you finished on time, you can leave early."}]'::jsonb,
 'a', '"As long as" con condiciones futuras usa presente simple, y necesita "as" en ambos lados.', 'No lleva "will" tras "as long as", y no puede faltar el segundo "as".'),
('C1', 6, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"De haberlo sabido, habría venido antes."',
 '[{"id":"a","key":"A","text":"Had I known, I would have come earlier."},{"id":"b","key":"B","text":"If I had known, I would come earlier."},{"id":"c","key":"C","text":"Had I know, I would have come earlier."},{"id":"d","key":"D","text":"I had known, I would have come earlier."}]'::jsonb,
 'a', 'La inversión "Had + sujeto + participio" sustituye a "if" en un tercer condicional formal.', 'El participio correcto es "known"; y sin "if" ni inversión, la oración queda incompleta.'),
('C1', 7, 'VOCABULARIO', 40, 'Elige la traducción correcta', '"Su actuación dejó mucho que desear."',
 '[{"id":"a","key":"A","text":"Her performance left a lot to be desired."},{"id":"b","key":"B","text":"Her performance left many to be desired."},{"id":"c","key":"C","text":"Her performance leaves a lot to be desired since."},{"id":"d","key":"D","text":"Her performance left a lot to desire."}]'::jsonb,
 'a', 'Es una expresión fija en pasado: "left a lot to be desired".', 'Se usa "a lot", no "many"; y la voz pasiva "to be desired" no puede omitirse.'),
('C1', 8, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Cuanto antes lo resolvamos, mejor para todos."',
 '[{"id":"a","key":"A","text":"The sooner we resolve it, the better for everyone."},{"id":"b","key":"B","text":"Sooner we resolve it, better for everyone."},{"id":"c","key":"C","text":"The more soon we resolve it, the better for everyone."},{"id":"d","key":"D","text":"The sooner we resolve it, the best for everyone."}]'::jsonb,
 'a', 'El comparativo doble exige "the" en ambas cláusulas y la forma comparativa correcta.', '"Soon" no forma comparativo con "more"; y no se usa el superlativo en esta estructura.'),
('C1', 9, 'VOCABULARIO', 40, 'Elige la traducción correcta', '"Lejos de resolver el problema, empeoró la situación."',
 '[{"id":"a","key":"A","text":"Far from solving the problem, it made things worse."},{"id":"b","key":"B","text":"Far to solve the problem, it made things worse."},{"id":"c","key":"C","text":"Far from solve the problem, it made things worse."},{"id":"d","key":"D","text":"Far of solving the problem, it made things worse."}]'::jsonb,
 'a', '"Far from" va seguido de gerundio, no infinitivo.', 'Tras "far from" se necesita la forma "-ing" del verbo, no el infinitivo ni otra preposición.'),
('C1', 10, 'VOCABULARIO', 40, 'Elige la traducción correcta', '"Me acusó de haber mentido."',
 '[{"id":"a","key":"A","text":"He accused me of having lied."},{"id":"b","key":"B","text":"He accused me to have lied."},{"id":"c","key":"C","text":"He accused me of lying before."},{"id":"d","key":"D","text":"He accused me for having lied."}]'::jsonb,
 'a', '"Accuse someone of" se combina con gerundio, incluyendo su forma perfecta "having + participio".', '"Accuse" se combina con "of", no con "to" ni "for".'),
('C1', 11, 'VOCABULARIO', 40, 'Elige la traducción correcta', '"Su comportamiento raya en lo absurdo."',
 '[{"id":"a","key":"A","text":"His behaviour borders on the absurd."},{"id":"b","key":"B","text":"His behaviour borders in the absurd."},{"id":"c","key":"C","text":"His behaviour border on the absurd."},{"id":"d","key":"D","text":"His behaviour borders on absurd."}]'::jsonb,
 'a', '"Border on" es la colocación correcta, y "the absurd" usa el artículo con adjetivo sustantivado.', 'La preposición correcta es "on", no "in"; y falta concordancia o el artículo "the".'),
('C1', 12, 'VOCABULARIO', 40, 'Elige la traducción correcta', '"No hace falta decir que el proyecto fue un éxito."',
 '[{"id":"a","key":"A","text":"Needless to say, the project was a success."},{"id":"b","key":"B","text":"Needless to saying, the project was a success."},{"id":"c","key":"C","text":"No need to say, the project was a success."},{"id":"d","key":"D","text":"Needless say, the project was a success."}]'::jsonb,
 'a', '"Needless to say" es una expresión fija que introduce una afirmación obvia.', 'La expresión fija exige "to say", no "to saying" ni otras variantes.'),
('C1', 13, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Debería haberlo consultado contigo antes."',
 '[{"id":"a","key":"A","text":"I ought to have consulted you beforehand."},{"id":"b","key":"B","text":"I ought to consulted you beforehand."},{"id":"c","key":"C","text":"I ought to have consult you beforehand."},{"id":"d","key":"D","text":"I ought have consulted you beforehand."}]'::jsonb,
 'a', '"Ought to have + participio" expresa un arrepentimiento formal sobre el pasado.', 'Falta el "have" o el verbo no está en participio; "ought" siempre lleva "to".'),
('C1', 14, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Apenas había salido cuando empezó a llover."',
 '[{"id":"a","key":"A","text":"No sooner had I left than it started to rain."},{"id":"b","key":"B","text":"No sooner I had left than it started to rain."},{"id":"c","key":"C","text":"No sooner had I left when it started to rain."},{"id":"d","key":"D","text":"No sooner had I left that it started to rain."}]'::jsonb,
 'a', '"No sooner" al inicio exige inversión, y se combina con "than", no "when" ni "that".', 'Sin la inversión correcta o con el conector equivocado, la estructura enfática falla.'),
('C1', 15, 'GRAMÁTICA', 40, 'Elige la traducción correcta', '"Es imprescindible que llegue a tiempo."',
 '[{"id":"a","key":"A","text":"It is imperative that he arrive on time."},{"id":"b","key":"B","text":"It is imperative that he arrives on time."},{"id":"c","key":"C","text":"It is imperative he arriving on time."},{"id":"d","key":"D","text":"It is imperative for he arrive on time."}]'::jsonb,
 'a', 'Tras expresiones como "it is imperative that", el subjuntivo usa el verbo en forma base.', 'El subjuntivo formal no lleva "-s" en tercera persona ni forma "-ing".'),
('C1', 16, 'VOCABULARIO', 40, 'Elige la traducción correcta', '"Su renuncia cogió a todos por sorpresa."',
 '[{"id":"a","key":"A","text":"His resignation caught everyone off guard."},{"id":"b","key":"B","text":"His resignation caught everyone off guarded."},{"id":"c","key":"C","text":"His resignation catches everyone off guard."},{"id":"d","key":"D","text":"His resignation caught everyone of guard."}]'::jsonb,
 'a', '"Catch someone off guard" es la colocación fija correcta.', 'La preposición correcta es "off", no "of"; y "guard" no lleva "-ed" en esta expresión.');
